name: CI

on:
  push:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1.4']
        julia-arch: [x64]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: setup
        run: julia --project -e 'using Pkg; Pkg.instantiate()'
      - name: run
        run: julia --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 1
      - name: run
        run: julia --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 2
      - name: run
        run: julia --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 3
      - name: run
        run: julia --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 4
      - name: run
        run: julia -O3 --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 1
      - name: run
        run: julia -O3 --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 2
      - name: run
        run: julia -O3 --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 3
      - name: run
        run: julia -O3 --project bench.jl
        env:
          OPENBLAS_NUM_THREADS: 1
          JULIA_NUM_THREADS: 4
